config/routes.rb
Rails.application.routes.draw do
  resources :girls
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/girl.rb
class Girl < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/girls_controller.rb
class GirlsController < ApplicationController
  before_action :set_girl, only: [:show, :edit, :update, :destroy]

  # GET /girls
  # GET /girls.json
  def index
    @girls = Girl.all
  end

  # GET /girls/1
  # GET /girls/1.json
  def show
  end

  # GET /girls/new
  def new
    @girl = Girl.new
  end

  # GET /girls/1/edit
  def edit
  end

  # POST /girls
  # POST /girls.json
  def create
    @girl = Girl.new(girl_params)

    respond_to do |format|
      if @girl.save
        format.html { redirect_to @girl, notice: 'Girl was successfully created.' }
        format.json { render :show, status: :created, location: @girl }
      else
        format.html { render :new }
        format.json { render json: @girl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /girls/1
  # PATCH/PUT /girls/1.json
  def update
    respond_to do |format|
      if @girl.update(girl_params)
        format.html { redirect_to @girl, notice: 'Girl was successfully updated.' }
        format.json { render :show, status: :ok, location: @girl }
      else
        format.html { render :edit }
        format.json { render json: @girl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /girls/1
  # DELETE /girls/1.json
  def destroy
    @girl.destroy
    respond_to do |format|
      format.html { redirect_to girls_url, notice: 'Girl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_girl
      @girl = Girl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def girl_params
      params.require(:girl).permit(:name, :number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/girls_helper.rb
module GirlsHelper
end

app/views/girls/_form.html.erb
<%= form_with(model: girl, local: true) do |form| %>
  <% if girl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(girl.errors.count, "error") %> prohibited this girl from being saved:</h2>

      <ul>
      <% girl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :girl_name %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :girl_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/girls/edit.html.erb
<h1>Editing Girl</h1>

<%= render 'form', girl: @girl %>

<%= link_to 'Show', @girl %> |
<%= link_to 'Back', girls_path %>

app/views/girls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Girls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @girls.each do |girl| %>
      <tr>
        <td><%= girl.name %></td>
        <td><%= girl.number %></td>
        <td><%= link_to 'Show', girl %></td>
        <td><%= link_to 'Edit', edit_girl_path(girl) %></td>
        <td><%= link_to 'Destroy', girl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Girl', new_girl_path %>
<script>
  alert("1");
</script>

app/views/girls/new.html.erb
<h1>New Girl</h1>

<%= render 'form', girl: @girl %>

<%= link_to 'Back', girls_path %>

app/views/girls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @girl.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @girl.number %>
</p>

<%= link_to 'Edit', edit_girl_path(@girl) %> |
<%= link_to 'Back', girls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>